### ISSUE TITLE
The problem of inconsistency in comparing the reproduced results and you provided.

### ISSUE THREAD

**Issue by Annlean** [meelgroup/mis#10]
Reproduce ApproxMC4 in the Linux environment, and use the CNF example you provided.  I found that the "Total time" is 0, and "Number of solutions is: 3*2**5" is inconsistent with the final result "s mc 96". In practice, as shown in the result your provided, the two calculations should be consistent. this is my result:
![image](https://github.com/meelgroup/mis/assets/48082418/38d43f80-2cdc-4009-8d4b-f43464bc1f7c)

**Comment by msoos** [comment]
Hi,

According to Python:

```
python
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 3*2**5
96
```

And indeed, 3 multiplied by 2^5 is: 2*32 = 96.

I hope the above helped!

Mate
