### ISSUE TITLE
Number of occurrence of each unique solution 

### ISSUE THREAD

**Issue by mohammadmonjil** [meelgroup/mis#9]
This is not exactly an issue but I would ask anyway. Using sampling on some variables I can know the number of unique solutions of those variables. But is it possible to count how many times each particular unique solution occurs? Let's say v1, v2, v3 are three unique solutions of some sampling variables. v1,v2,v3 appear n1,n2,n3 times, Is it possible to calculate n1,n2,n3?

**Comment by msoos** [comment]
Hi,

Your example is not very clear. Let's say these are the solutions, where the columns are: v1, v2, v3, n1, n2, n3
```
000 111
000 110
001 111
001 110
001 100
101 100
```

So what do you want to know? something like this?

```
000 -> 1
001 -> 3
101 -> 1
```

So how many times each projected solution appeared in the full solution space? This would make sense, but... how do you do this efficiently? Say, there are 2^200 solutions over the projection variables, and each occurs exactly 1,2,3...2**200 times in the full solution space. Representing this array would require 2^200 x 200 bits. That likely would require a computer that has more atoms than the atoms in the known universe. Unfortunately, it is not at all impossible to have this kind of issue -- i.e. many solutions, with very different numbers. So... what should we do?

What you can of course do is to call the counter with v1..v3 set to e.g. `000` and then it will return `1` for the count, then set it to `001` and it will return `3` for the count, etc. This is slow. We could change GANAK to do this which would be much faster to count. However, it's a lot of effort.

Note that MIS is not the tool you want to use at all. You want to use [GANAK](https://github.com/meelgroup/ganak) or [ApproxMC](https://github.com/meelgroup/approxmc) to do such counting

Unfortunately, I can't help you much more than what's above, so I am closing. In case still relevant, please open a well-described, precise issue in ApproxMC or GANAK, explaining the problem precisely, in detail, with examples, so I don't accidentally misunderstand it. However, if your question is what's above, then that's complicated to do, and may be impossible given the space needs, and I can't help with it currently unless there is some very compelling reason to do so.

I hope the above helped,

Mate
